#pragma once

#include "ExportDefinitions.hpp"
#include <iostream>
#include <string>
#include <memory>
#include <unordered_map>
#include <chrono>
#include <vector>
#include <exception>
#include <boost/uuid/uuid.hpp>
#include <boost/algorithm/string.hpp>
#include <boost/uuid/uuid_generators.hpp>
#include <boost/uuid/uuid_io.hpp>
#include <boost/beast/core.hpp>
#include <boost/beast/http.hpp>
#include <boost/asio.hpp>
#include <thread>
#include <atomic>